It seems like I succeeded in suppressing the IndexOutOfBounds exception, so the user is not affected by it. It's still there though, but I can't figure out what the root cause of it is.
I see this one a lot less:
java.lang.IllegalArgumentException: Width and height must be >= 0

But it still happens occasionally.